export interface AchievementDefinition {
  id: string
  title: string
  description: string
  emoji: string
  xpReward: number
  category: string
  criteria: string
}

export const ACHIEVEMENTS: AchievementDefinition[] = [
  {
    id: 'first_task',
    title: 'Primeira Missão!',
    description: 'Completou a sua primeira tarefa doméstica.',
    emoji: '🎯',
    xpReward: 50,
    category: 'tasks',
    criteria: 'complete_tasks_total:1',
  },
  {
    id: 'full_cleaning_day',
    title: 'Mestre da Vassoura',
    description: 'Completou todas as tarefas de limpeza em um único dia.',
    emoji: '🧹',
    xpReward: 100,
    category: 'tasks',
    criteria: 'complete_all_cleaning_tasks_in_day',
  },
  {
    id: 'first_guide',
    title: 'Aprendiz do Lar',
    description: 'Leu o seu primeiro guia doméstico.',
    emoji: '📖',
    xpReward: 30,
    category: 'guides',
    criteria: 'read_guides_total:1',
  },
  {
    id: 'emergency_used',
    title: 'Sobrevivente',
    description: 'Usou o Botão de Emergência pela primeira vez.',
    emoji: '🚨',
    xpReward: 20,
    category: 'emergency',
    criteria: 'use_emergency_button:1',
  },
  {
    id: 'seven_day_streak',
    title: 'Mantendo a Rotina',
    description: 'Completou tarefas por 7 dias consecutivos.',
    emoji: '🔥',
    xpReward: 150,
    category: 'streak',
    criteria: 'streak_days:7',
  },
  {
    id: 'diagnostic_done',
    title: 'Autoconhecimento',
    description: 'Completou o diagnóstico inicial do app.',
    emoji: '🧠',
    xpReward: 40,
    category: 'onboarding',
    criteria: 'complete_diagnostic',
  },
  {
    id: 'reached_apprentice',
    title: 'Aprendendo',
    description: 'Chegou ao nível Aprendiz.',
    emoji: '🌱',
    xpReward: 0,
    category: 'level',
    criteria: 'reach_level:apprentice',
  },
  {
    id: 'reached_independent',
    title: 'Independente',
    description: 'Chegou ao nível Independente.',
    emoji: '🏠',
    xpReward: 0,
    category: 'level',
    criteria: 'reach_level:independent',
  },
  {
    id: 'reached_master',
    title: 'Mestre da Casa 👑',
    description: 'Chegou ao nível máximo. A casa é sua!',
    emoji: '👑',
    xpReward: 0,
    category: 'level',
    criteria: 'reach_level:master',
  },
  {
    id: 'five_guides_read',
    title: 'Biblioteca do Lar',
    description: 'Leu 5 guias domésticos diferentes.',
    emoji: '📚',
    xpReward: 80,
    category: 'guides',
    criteria: 'read_guides_total:5',
  },
  {
    id: 'thirty_day_streak',
    title: 'Força de Hábito',
    description: 'Completou tarefas por 30 dias consecutivos.',
    emoji: '💪',
    xpReward: 500,
    category: 'streak',
    criteria: 'streak_days:30',
  },
  {
    id: 'first_cook',
    title: 'Chef de Si Mesmo',
    description: 'Completou uma tarefa da categoria cozinha pela primeira vez.',
    emoji: '🍳',
    xpReward: 60,
    category: 'tasks',
    criteria: 'complete_tasks_category:kitchen:1',
  },
  {
    id: 'organized_week',
    title: 'Semana Redonda',
    description: 'Não deixou nenhuma tarefa pendente durante uma semana inteira.',
    emoji: '✅',
    xpReward: 200,
    category: 'tasks',
    criteria: 'zero_pending_tasks_week:1',
  },
  {
    id: 'hundred_tasks',
    title: 'Centenário',
    description: 'Completou 100 tarefas ao longo do tempo.',
    emoji: '💯',
    xpReward: 300,
    category: 'tasks',
    criteria: 'complete_tasks_total:100',
  },
  {
    id: 'budget_guide_read',
    title: 'Bolso Esperto',
    description: 'Leu um guia sobre finanças domésticas.',
    emoji: '💰',
    xpReward: 50,
    category: 'guides',
    criteria: 'read_guides_category:finance:1',
  },
  {
    id: 'profile_complete',
    title: 'Quem Sou Eu',
    description: 'Preencheu todas as informações do perfil.',
    emoji: '😊',
    xpReward: 25,
    category: 'onboarding',
    criteria: 'complete_profile',
  },
  {
    id: 'night_owl',
    title: 'Coruja Arrumada',
    description: 'Completou uma tarefa depois das 22h.',
    emoji: '🦉',
    xpReward: 35,
    category: 'tasks',
    criteria: 'complete_task_after_hour:22',
  },
]
